#!/bin/bash

# basic script to mangle environment
# Copyright 2012 Jo Shields
# Licensed under WTFPL v2

shtest=$(expr \"$0\" : '.*sh')
if [ "$shtest" -eq "0" ]
then
        echo "This script will help you to set up your environment to use a"
	echo "snapshot package of Mono. To use it, run:"
	echo
	echo -e "\t. $(basename $0) APP/VER"
	echo
	echo "You have the following possible combinations of APP/VER:"
	echo
	cd /usr/share/mono-snapshot/packages.d/ && ls */* | sed 's/^/\t/'
	echo
	echo "Calling APP without specifying VER will load the latest version"
	exit 0
fi

VER=$1
vertest=$(expr length "$VER")
if [[ "$vertest" -eq "0" ]]
then
	echo "You must specify a snapshot to use"
	return 1
fi
if [ `expr index ${VER} "/"` -eq 0 ]
then
	if [ -d "/usr/share/mono-snapshot/packages.d/${VER}" ]
	then
		VER=$1/$(basename `ls /usr/share/mono-snapshot/packages.d/${VER}/* | tail -1`)
	else
		echo "You must specify a valid app (no app ${VER} found)"
		return 1
	fi
fi
if [ -e "/usr/share/mono-snapshot/packages.d/${VER}" ]
then
	. /usr/share/mono-snapshot/packages.d/${VER}
else
	echo "You must specify a valid app version (no app ${VER} found)"
	return 1
fi
